global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load all scrape configurations from the 'conf.d' directory.
# This ensures a modular and clean setup where each target or group of
# targets has its own configuration file.
scrape_config_files:
  - /etc/prometheus/conf.d/*.yml 